### ndarray 생성 

In [1]:
import numpy as np 

In [3]:
arr = np.array([1,2,3,4]) #numpy배열이다. 
print(arr) 
print(type(arr)) #그냥 리스트랑 기능이나 성능면에서 차이가 많이 난다. 

[1 2 3 4]
<class 'numpy.ndarray'>


0으로 초기화된 배열 


In [4]:
arr = np.zeros((3,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


빈 값으로 만들어진 배열


In [7]:
arr = np.empty((2,2)) #다른 프로그램이 사용했던 찌꺼기가 보인다. 
print(arr) # 새로운 값으로 다 채울거면 굳이 0으로 초기화 안하는 게 좋다. 
# 0을 추가하는 것도 다 연산이 되니까. 

[[4.9e-324 9.9e-324]
 [1.5e-323 2.0e-323]]


1로 가득찬 배열


In [8]:
arr = np.ones((3,3)) 
print(arr) 

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


배열의 생성 


In [9]:
# arr = np.array([0,1,2,3,4,5,6,7,8,9])
arr = np.arange(10) 
print(arr) # 결과는 numpy배열 

[0 1 2 3 4 5 6 7 8 9]


ndarray 배열의 모양, 차수, 데이터 타입 확인 


In [15]:
arr = np.array([[1,2,3],[4,5,6]]) # 정수형 배열 
print(arr)

[[1 2 3]
 [4 5 6]]


In [12]:
arr.shape 

(2, 3)

In [13]:
arr.ndim

2

In [14]:
arr.dtype #정수형 

dtype('int64')

데이터 타입 변경 


In [16]:
arr_float = arr.astype(np.float64) # 숫자가 클수록 표현 범위가 높아진다.  
arr_float.dtype 

dtype('float64')

In [17]:
arr_str = np.array(['1','2','3'])
arr_str.dtype

dtype('<U1')

In [18]:
arr_int = arr_str.astype(np.int64) 
arr_int.dtype

dtype('int64')

### ndarray 배열의 연산 

In [21]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

arr1 + arr2 

array([[ 6,  8],
       [10, 12]])

In [22]:
np.add(arr1,arr2) #명령으로 덧셈하기 

array([[ 6,  8],
       [10, 12]])

In [23]:
arr1 * arr2 

array([[ 5, 12],
       [21, 32]])

In [24]:
np.multiply(arr1, arr2) 

array([[ 5, 12],
       [21, 32]])

슬라이싱 

슬라이싱한 배열은 원본 배열의 뷰이다. 슬라이싱한 배열을 수정하면 원본 배열도 바뀐다.

뷰가 아닌 새로운 배열을 생성하려면 arr[:2,1:3].copy() 와 같은 함수를 사용해야 한다. 

In [30]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

arr_1 = arr[:2,1:3]
print(arr_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]


In [26]:
arr.ndim

2

In [27]:
arr[0,2]

3

In [28]:
arr[:2,1:-1]

array([[2],
       [5]])

In [29]:
arr[[0,1,2],[2,0,1]] #[0,1,2]는 row부분 결정, [2,0,1]은 column부분 결정

array([3, 4, 8])

In [31]:
idx = arr > 3 
print(idx) 

[[False False False]
 [ True  True  True]
 [ True  True  True]]


In [32]:
arr[idx] 

array([4, 5, 6, 7, 8, 9])

### wine quality 데이터 불러오기

np라이브러리 안에 loadtxt함수를 실행하여 텍스트 파일을 불러올 수 있음. 

nupmy로 데이터를 가져온 후에는 sum, mean 과 같은 일반적인 통계함수를 사용할 수 있음. 

In [39]:
redwine = np.loadtxt(fname = 'winequality-red.csv', delimiter=';', skiprows = 1 ) # 구별자는 세미콜론, 첫 줄은 헤더라서 무시하고 넘어가기 위해 skiprows.
print(redwine)

[[ 7.4    0.7    0.    ...  0.56   9.4    5.   ]
 [ 7.8    0.88   0.    ...  0.68   9.8    5.   ]
 [ 7.8    0.76   0.04  ...  0.65   9.8    5.   ]
 ...
 [ 6.3    0.51   0.13  ...  0.75  11.     6.   ]
 [ 5.9    0.645  0.12  ...  0.71  10.2    5.   ]
 [ 6.     0.31   0.47  ...  0.66  11.     6.   ]]


합계 

In [41]:
print(redwine.sum()) # 전체 데이터에 대한 합 

152084.78194


In [42]:
print(redwine.mean())

7.926036165311652


In [43]:
redwine.shape

(1599, 12)

축 

In [44]:
print(redwine.mean(axis=0)) # 0이 기준이니까 column끼리 더함. 

[ 8.31963727  0.52782051  0.27097561  2.5388055   0.08746654 15.87492183
 46.46779237  0.99674668  3.3111132   0.65814884 10.42298311  5.63602251]


In [45]:
print(redwine.mean(axis=1))

[ 6.21198333 10.25456667  8.30825    ...  8.37347833  8.76795583
  7.7077075 ]


슬라이싱 

In [47]:
redwine[:, 0] # 1번째 컬럼 

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

In [48]:
redwine[:, 0].mean() # 1번째 컬럼 

8.31963727329581

In [50]:
redwine.max(axis = 0)

array([ 15.9    ,   1.58   ,   1.     ,  15.5    ,   0.611  ,  72.     ,
       289.     ,   1.00369,   4.01   ,   2.     ,  14.9    ,   8.     ])